#!/bin/bash

if ping -c 1 n320 &> /dev/null
then
  echo "Shutting down USRP N320 device..."
  ssh n320 "shutdown -h now"
  sleep 15
else
  echo "USRP N320 doesn't answer, Hard switch off"
fi

rhubarbe script pdu-off 2 0
